server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    data-username: root
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null  # jackson 非空
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: G:/tmp/ssh/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:                     # 保证生成的id不重复,在每个部署的节点都配置机器id
    workerId: 1
    dataCenterId: 1
  pay:
    appID: wx8397f8696b538317
    mchID: 147326802
    key: T69iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 8000
    notifyUrl: http://a5trqu.natappfree.cc/notify/pay   # 工具生成的内网穿透 提供外网访问的域名和接口

